/*  =========================================================================
    zenstore - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of zenstore - ZeroMQ based encrypted store.      
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef ZNS_LIBRARY_H_INCLUDED
#define ZNS_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <sodium.h>

//  ZNS version macros for compile-time API detection
#define ZNS_VERSION_MAJOR 0
#define ZNS_VERSION_MINOR 1
#define ZNS_VERSION_PATCH 0

#define ZNS_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZNS_VERSION \
    ZNS_MAKE_VERSION(ZNS_VERSION_MAJOR, ZNS_VERSION_MINOR, ZNS_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZNS_STATIC
#       define ZNS_EXPORT
#   elif defined ZNS_EXPORTS
#       define ZNS_EXPORT __declspec(dllexport)
#   else
#       define ZNS_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZNS_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZNS_BUILD_DRAFT_API
#define ZNS_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZNS_BUILD_DRAFT_API
typedef struct _zns_store_t zns_store_t;
#define ZNS_STORE_T_DEFINED
typedef struct _zns_srv_t zns_srv_t;
#define ZNS_SRV_T_DEFINED
#endif // ZNS_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZNS_BUILD_DRAFT_API
#include "zns_store.h"
#include "zns_srv.h"
#endif // ZNS_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
