/*  =========================================================================
    zenstore - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef ZNS_LIBRARY_H_INCLUDED
#define ZNS_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <sodium.h>

//  ZNS version macros for compile-time API detection

#define ZNS_VERSION_MAJOR 0
#define ZNS_VERSION_MINOR 1
#define ZNS_VERSION_PATCH 0

#define ZNS_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZNS_VERSION \
    ZNS_MAKE_VERSION(ZNS_VERSION_MAJOR, ZNS_VERSION_MINOR, ZNS_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZNS_STATIC
#       define ZNS_EXPORT
#   elif defined ZNS_EXPORTS
#       define ZNS_EXPORT __declspec(dllexport)
#   else
#       define ZNS_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZNS_EXPORT
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases


//  Public classes, each with its own header file

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
